OPS-5806 - Added environment variables for dev and production
UN-OCHA/hrinfo_app pull request #21
Opened 2019-07-16 14:10 UTC by guillaumev

According to the documentation (https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables), .env.development will be picked up when running yarn start while .env.production will be picked up when running yarn build.
Given that the Dockerfile is running yarn build, I'm not sure how we can make 2 versions of the Dockerfile: one for development running yarn start and another one for production running yarn build ?

2019-07-16 14:36 UTC, attiks approved these changes
I assume @teodorescuserban will just set env variables inside docker

2019-07-16 15:37 UTC, teodorescuserban requested changes
I am sorry, it is no good.
There is no yarn start.
The hrinfo app is being built into the docker image.
The environmental variables are to be inserted later on, when a new container is created (depending on which stack is created in).
But at that time there is no node process anymore, only static files.
You need to rely on a js file that defines the respective variable. You need to include this in your main js file.
This file will get mapped from the stack on the host - this is currently being used in HPC apps (rpm, ftsadmin, etc), which will allow the customisation of the variables.

this is the content of that file for rpm prod:

```
var appConfig= {
  "angularModule": "rpm",
  ...
};
```

2019-07-17 08:39 UTC, guillaumev commented
@teodorescuserban Would it be possible to take the .env.development file and copy it to a .env file, and then remove the .env.development file for development builds, same for production but of course with .env.production ? I'm asking because it seems like it would stick a bit closer to the standard React workflow for env variables...

2019-07-17 08:41 UTC, teodorescuserban commented
There is no react when the container runs. Only the artefacts left from the build process.
And we want to have a single, identical image for all environments, so it is not possible at build time to decide which env file goes active anyway.

2019-07-17 09:33 UTC, guillaumev commented
@teodorescuserban Thank you, but I still don't really understand how this would work with a separate javascript file. I believe it's the same kind of setup as the HID app, but I looked at the HID app build process and I don't understand how you are able to create the dev image even though the Dockerfile seems to run grunt --target=production all the time...

2019-07-17 09:35 UTC, teodorescuserban commented
Here is the config from stack overwriting the config folder inside app: https://github.com/UN-OCHA/hid-stack/blob/master/env/prod/common/common_web.yml#L26 <https://github.com/UN-OCHA/hid-stack/blob/master/env/prod/common/common_web.yml#L26>

- Serban

> On 17 Jul 2019, at 12:33, Guillaume Viguier-Just <notifications@github.com> wrote:
> 
> @teodorescuserban <https://github.com/teodorescuserban> Thank you, but I still don't really understand how this would work with a separate javascript file. I believe it's the same kind of setup as the HID app, but I looked at the HID app build process and I don't understand how you are able to create the dev image even though the Dockerfile seems to run grunt --target=production all the time...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/UN-OCHA/hrinfo_app/pull/21?email_source=notifications&email_token=AALYWSFFIPKRMB6FNHS7ZX3P73RONA5CNFSM4IEBMSDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2DTZSY#issuecomment-512179403>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AALYWSFCPTZ2GEJJJDJQUR3P73RONANCNFSM4IEBMSDA>.
>

2019-07-17 09:54 UTC, teodorescuserban requested changes
Ok, much better.
You only need to ensure there is a valid config.js file at build time (maybe use prod as default?) to make absoltely sure that build-time tests or other tests dont throw errors due to missing variable.

2019-07-17 10:06 UTC, teodorescuserban approved these changes
⭐️

2019-07-29 09:53 UTC, merged